# Generated using: code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension ardenivanov.svelte-intellisense
code --install-extension bierner.markdown-preview-github-styles
code --install-extension castwide.solargraph
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension FerrierBenjamin.fold-unfold-all-icone
code --install-extension file-icons.file-icons
code --install-extension flowtype.flow-for-vscode
code --install-extension ionutvmi.path-autocomplete
code --install-extension JamesBirtles.svelte-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension naumovs.color-highlight
code --install-extension naumovs.theme-oceanicnext
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension wix.vscode-import-cost
